### ISSUE TITLE
Handling DOIs for restricted records

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/product-rdm#178]
A record might get a DOI reserved when creating a draft. However, then the access rules might change. The use cases are the following:

- [ ] A draft gets a reserved DOI, but then it changes access to `embargoed`.
- [ ] A record gets a reserved DOI, but then it changes access to `embargoed`. Can this happen, the record access cannot changed, when published?
- [ ] A drafts gets a reserved DOI, but then it changes to access to `restricted`
- [ ] Once the embargo is lifted how does the DOI gets registered?

Related issues:
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2129
- [ ] Ensure that we can easily add Crossref provider

**Comment by lnielsen** [comment]
Discussion from the coffee break at the InvenioRDM workshop with Werner, Nico, Martin, Karolina and Christoph. 

Proposed solution:
- Restricted records: DOIs are **not** created, and hence also not registered.
- Restricted records with embargo: DOIs are **not** created, and hence also not registered.
- Public with restricted files (w/wo embargo): DOIs are created and registered when published.
- Public: DOIs are created and registered when published.

State changes:
- Restricted -> Public (e.g. user changes the setting or embargo expire): No DOI is created automatically.
- Public -> Restricted (e.g. user changes visibility setting): A general warning is displayed to the user that they should be aware that a DOI is registered and metadata may have been harvested by several systems and there's no control of what happens.

**Comment by chriz-uniba** [comment]
Can someone shortly explain:
- "Restricted -> Public (e.g. user changes the setting or embargo expire): No DOI is created automatically."

- Why did you decide to not create a DOI in this case?
- Will there be a way to create it manually?

**Comment by fenekku** [comment]
+1 on @chriz-uniba comments. Apart from that the rest of the approach seems good and we would like to see that happen at NU. We are willing to lend a hand.

**Comment by chokribr** [comment]
Datacite identify three states for registered metadata:

**publish** | Triggers a state move from draft or registered to findable
**register** | Triggers a state move from draft to registered
**hide** | Triggers a state move from findable to registered

to Move from published to restricted we can use the "hide" state this will make metadata no longer available and findable  via the Public API but they will stay viewable by members!
https://support.datacite.org/docs/doi-states
