### ISSUE TITLE
Zoomable image previewer (IIIF) with caching of titled images

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#185]
### Goals:
- Integrate the Mirador IIIF image previewer for zooming on images
- Developed a feature to process images in the background to create tiled pyramid TIFFs.
- Integrate an external IIIF image server.

Overall this should ensure thumbnails as well as image tiles for the zoomable images have been pre-generated and thus can served fast.

### Context

The  work will be primarily focused on the background image processing. A lot of work was already done for the generation of IIIF Manifests as well as on the image previewer. The current solution is however too slow to launch for a larger audience which thus requires more extensive caching of images.

The goal is to deploy it on Zenodo which includes processing of all images on Zenodo.

### Responsible

CERN is responsible for task.

### Resources

About 3-4 people over 4 weeks is allocated to the task.

**Comment by Herrner** [comment]
Will this work without an external image server? Or is this just an option since "The goal is to deploy it on Zenodo which includes processing of all images on Zenodo."?

**Comment by lnielsen** [comment]
@Herrner Sorry for the late reply. It will not work without the external image server since we need the server for maximising performance. 

Here's an example of a 50k x 50k px image: https://zenodo.org/records/11307027
