### ISSUE TITLE
EOSC AAI integration

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#64]
- Integrate the EOSC authentication.

**Comment by lnielsen** [comment]
Docs missing integration, but otherwise ready to go.

**Comment by slint** [comment]
- Invenio-OAuthClient [v1.5.4 released](https://pypi.org/project/invenio-oauthclient/1.5.4/) with OpenAIRE AAI contrib module
- Docs merged under `Customize > Authentication`. Pending next docs deployment
