### ISSUE TITLE
Files: Bulk download all

### ISSUE THREAD

**Issue by Herrner** [inveniosoftware/product-rdm#86]
We advice people not to upload their data in .zip files so that people can decide what to download, but this makes it harder for people to download the whole thing (without using a "download all" extension).   

It would be nice to have a "download all" button, or, even better, let users select which files to download as a bulk.  I haven't found a way to download more than one file with a browser without packing them in some kind of archive beforehand, tough...

**Comment by lnielsen** [comment]
Could potentially be solved with having OCFL objects written to disk as zip files and serve out the OCFL object

**Comment by dfdan** [comment]
The structure of a true OCFL object is likely to confuse end-users (especially where the it represents multiple versions of the record). The zip would have inventory file(s) and (potentially multiple) content sub-directories (for different versions) which would contain different files depending on which version they were introduced with. A user would either have to read+understand the inventory, or go searching manually for the file(s) they want.

However it is likely the same logic could produce a consolidated content folder for the required version, and return only that. I think this is probably more in line with what end users would expect?

**Comment by lnielsen** [comment]
Done
